### ISSUE TITLE
Cleanup Dockerfile

### ISSUE THREAD

**Issue by amitaibu** [shoov/php-ci#5]
We should still use ubuntu, but lets cleanup whatever is not needed (e.g. zsh)

Also, the [original](https://github.com/tomav/docker-behat) Dockerfile had the non-root user -- please investigate if this is indeed a best practice.

**Comment by amitaibu** [comment]
@solker

**Comment by solker** [comment]
@amitaibu 

> This means that in most cases, containers will not need “real” root privileges at all.
> 
> The best practice for users would be to remove all capabilities except those explicitly required for their processes.

(c) https://docs.docker.com/articles/security/

**Comment by solker** [comment]
If we are using zsh to debug and other stuff i don't know who we can to clean.

**Comment by amitaibu** [comment]
zsh is not really needed.

Also the docker file might be improved by having the apt-get of multiple items on single command -- having smaller images will result with quicker deploy - but don't invest too much time in optimizing this.
